/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('primevue/button')['default']
    Card: typeof import('primevue/card')['default']
    Column: typeof import('primevue/column')['default']
    CompletionCard: typeof import('./src/components/CompletionCard.vue')['default']
    DataTable: typeof import('primevue/datatable')['default']
    DeleteDialog: typeof import('./src/components/DeleteDialog.vue')['default']
    Dialog: typeof import('primevue/dialog')['default']
    Form: typeof import('@primevue/forms/form')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    IconField: typeof import('primevue/iconfield')['default']
    Image: typeof import('primevue/image')['default']
    InputIcon: typeof import('primevue/inputicon')['default']
    InputText: typeof import('primevue/inputtext')['default']
    Message: typeof import('primevue/message')['default']
    NewQuestionDialog: typeof import('./src/components/NewQuestionDialog.vue')['default']
    QuestionCard: typeof import('./src/components/QuestionCard.vue')['default']
    QuestionsTable: typeof import('./src/components/QuestionsTable.vue')['default']
    SplitButton: typeof import('primevue/splitbutton')['default']
    Tests: typeof import('./src/components/tests.vue')['default']
    Toast: typeof import('primevue/toast')['default']
    ToggleButton: typeof import('primevue/togglebutton')['default']
    ToggleSwitch: typeof import('primevue/toggleswitch')['default']
    Toolbar: typeof import('primevue/toolbar')['default']
  }
  export interface ComponentCustomProperties {
    AnimateOnScroll: typeof import('primevue/animateonscroll')['default']
  }
}
